import React from 'react';
import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "About",
    description: "Generated by create next app",
};

export default function About() {
    return (
        <div>
            <div className="flex justify-center items-center mx-auto h-screen w-screen">
                <h1>About</h1>
            </div>
        </div>
    );
}
